In [1]:
import numpy as np
import matplotlib.pyplot as plt

import tensorflow as tf

In [2]:
x = tf.Variable(4.0)

with tf.GradientTape() as tape:
    y = x**2

y

<tf.Tensor: shape=(), dtype=float32, numpy=16.0>

In [3]:
dy_dx = tape.gradient(y, x)

dy_dx

<tf.Tensor: shape=(), dtype=float32, numpy=8.0>

In [4]:
w = tf.Variable(tf.random.normal((4, 2)))

w

<tf.Variable 'Variable:0' shape=(4, 2) dtype=float32, numpy=
array([[-2.4982426,  1.7598327],
       [ 1.3411921,  0.6966203],
       [ 0.7098624, -1.8340112],
       [-1.0298057, -1.8976494]], dtype=float32)>

In [5]:
b = tf.Variable(tf.ones(2, dtype=tf.float32))

b

<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([1., 1.], dtype=float32)>

In [6]:
x = tf.Variable([[10., 20., 30., 40.]], dtype=tf.float32)

x

<tf.Variable 'Variable:0' shape=(1, 4) dtype=float32, numpy=array([[10., 20., 30., 40.]], dtype=float32)>

In [7]:
with tf.GradientTape(persistent=True) as tape:
    y = tf.matmul(x, w) + b

    loss = tf.reduce_mean(y**2)

In [8]:
[dl_dw, dl_db] = tape.gradient(loss, [w, b])

dl_dw, dl_db

(<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
 array([[ -170.54938,  -983.95575],
        [ -341.09875, -1967.9115 ],
        [ -511.64813, -2951.8672 ],
        [ -682.1975 , -3935.823  ]], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-17.054937, -98.39558 ], dtype=float32)>)

In [9]:
layer = tf.keras.layers.Dense(2, activation='relu')
x = tf.constant([[10., 20., 30.]])

In [10]:
with tf.GradientTape() as tape:
    y = layer(x)

    loss = tf.reduce_sum(y**2)

grad = tape.gradient(loss, layer.trainable_variables)

In [11]:
grad

[<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[0., 0.],
        [0., 0.],
        [0., 0.]], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([0., 0.], dtype=float32)>]

In [12]:
x1 = tf.Variable(5.0)

x1

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=5.0>

In [13]:
x2 = tf.Variable(5.0, trainable=False)

x2

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=5.0>

In [14]:
x3 = tf.add(x1, x2)

x3

<tf.Tensor: shape=(), dtype=float32, numpy=10.0>

In [16]:
x4 = tf.constant(5.0)

x4

<tf.Tensor: shape=(), dtype=float32, numpy=5.0>

In [17]:
with tf.GradientTape() as tape:
        y = (x1**2) + (x2**2) + (x3**2) + (x4**2)

grad = tape.gradient(y, [x1, x2, x3, x4])

grad

[<tf.Tensor: shape=(), dtype=float32, numpy=10.0>, None, None, None]

In [18]:
x1 = tf.constant(5.0)

x2 = tf.Variable(3.0)

In [19]:
with tf.GradientTape() as tape:
    tape.watch(x1)

    y = (x1**2) + (x2**2)

[dy_dx1, dy_dx2] = tape.gradient(y, [x1, x2])

[dy_dx1, dy_dx2]

[<tf.Tensor: shape=(), dtype=float32, numpy=10.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=6.0>]

In [20]:
with tf.GradientTape(watch_accessed_variables=False) as tape:
    tape.watch(x1)

    y = (x1**2) + (x2**2)

[dy_dx1, dy_dx2] = tape.gradient(y, [x1, x2])

[dy_dx1, dy_dx2]

[<tf.Tensor: shape=(), dtype=float32, numpy=10.0>, None]

In [21]:
x = tf.constant(1.0)
x1 = tf.Variable(5.0)
x2 = tf.Variable(3.0)

In [22]:
with tf.GradientTape(persistent=True) as tape:
    tape.watch(x)

    if x > 0.0:
        result = x1**2
    else:
        result = x2**2

dx1, dx2 = tape.gradient(result, [x1, x2])

dx1, dx2

(<tf.Tensor: shape=(), dtype=float32, numpy=10.0>, None)

In [23]:
x = tf.constant(-1.0)
x1 = tf.Variable(5.0)
x2 = tf.Variable(3.0)

In [24]:
with tf.GradientTape(persistent=True) as tape:
    tape.watch(x)

    if x > 0.0:
        result = x1**2
    else:
        result = x2**2

dx1, dx2 = tape.gradient(result, [x1, x2])

dx1, dx2

(None, <tf.Tensor: shape=(), dtype=float32, numpy=6.0>)

In [25]:
x = tf.Variable(2.)
y = tf.Variable(3.)

with tf.GradientTape() as tape:
    z = y * y

    dy_dx = tape.gradient(z, x)

print(dy_dx)

None
